#!/bin/sh
#
# Install a full smartos-vmtools
#

PROGNAME=`basename $0`
INSTALLER_DIR=`dirname $0`
DEST_DIR=/opt/smartos-vmtools
USAGE="usage: $0"

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# move the actual files into place
rm -rf $DEST_DIR/* || error_exit "Cannot remove contents of $DEST_DIR"
mkdir -p $DEST_DIR || error_exit "Cannot create $DEST_DIR"
cp -R $INSTALLER_DIR $DEST_DIR || error_exit "Cannot install to $DEST_DIR"
rm -f $DEST_DIR/$PROGNAME

# rm -f before ln -sf is required for solaris 9
rm -f $LIB_DIR/mdata-get

mkdir -p $LIB_DIR
ln -sf $INSTALLER_DIR/bin/mdata-get $LIB_DIR || \
  error_exit "Cannot link mdata-get to $LIB_DIR"

exit 0
