#!/bin/sh
#
# Install a full smartos-vmtools
#

PROGNAME=`basename $0`
INSTALLER_DIR=`dirname $0`
DEST_DIR=/opt/smartos-vmtools
OMNIBUS="$DEST_DIR"
EMBEDDED="$OMNIBUS/embedded"
USAGE="usage: $0"

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# move the actual files into place
rm -rf $DEST_DIR/* || error_exit "Cannot remove contents of $DEST_DIR"
mkdir -p $DEST_DIR || error_exit "Cannot create $DEST_DIR"
cp -R $INSTALLER_DIR $DEST_DIR || error_exit "Cannot install to $DEST_DIR"
rm -f $DEST_DIR/$PROGNAME

# rm -f before ln -sf is required for solaris 9
rm -f $LIB_DIR

mkdir -p `dirname $LIB_DIR`
ln -sf $EMBEDDED/lib/smartdc $LIB_DIR || \
  error_exit "Cannot link $EMBEDDED/lib/smartdc to $LIB_DIR"

for bin in mdata-delete mdata-get mdata-list mdata-put ; do
  ln -sf $OMNIBUS/bin/$bin /usr/sbin/$bin || \
    error_exit "Cannot link $bin to /usr/sbin/$bin"
done ; unset bin

exit 0
